/*
 * Test.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package de.uniluebeck.itcrl.tstk.backend.schema

data class Test(
    val firstName: String,
    val lastName: String,
    /** Age in years */
    val age: Long? = null,
    val hairColor: HairColor? = null
) {

    init {
        if (age != null)
            require(age >= 0L) { "age < minimum 0 - $age" }
    }

    enum class HairColor {
        black,
        brown,
        blue
    }

}
